aggregator:
  kafka:
    bootstrap-servers: "localhost:9092"
    topic:
      user: stats.user-actions.v1
      event: stats.events-similarity.v1
    producer-properties:
      "bootstrap.servers": ${aggregator.kafka.bootstrap-servers}
      "key.serializer": org.apache.kafka.common.serialization.StringSerializer
      "value.serializer": ru.practicum.serializer.GeneralAvroSerializer
    consumer-properties:
      "bootstrap.servers": ${aggregator.kafka.bootstrap-servers}
      "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
      "value.deserializer": ru.practicum.deserializer.UserActionDeserializer
      "group.id": aggregator-group

logging:
  level:
    ru.yandex.practicum: TRACE
    org.apache.kafka: ERROR

server:
  port: 0