CREATE SCHEMA IF NOT EXISTS requests;

CREATE TABLE IF NOT EXISTS requests.event_requests (
                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                              event_id BIGINT NOT NULL,
                                              created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                              requester_id BIGINT NOT NULL,
                                              status VARCHAR(50) NOT NULL,
    CONSTRAINT pk_event_requests PRIMARY KEY (id)
    );