CREATE SCHEMA IF NOT EXISTS events;

CREATE TABLE IF NOT EXISTS events.categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events.events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(120)                            NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT                                  NOT NULL
        CONSTRAINT events_categories_id_fk references events.categories,
    confirmed_requests INT     DEFAULT 0,
    created_on         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description        VARCHAR(7000),
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    paid               BOOLEAN DEFAULT false,
    participant_limit  INT     DEFAULT 0,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN DEFAULT false,
    state              VARCHAR(50)                             NOT NULL,
    lat                FLOAT,
    lon                FLOAT,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events.compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    pinned BOOLEAN DEFAULT false,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events.event_compilations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id       BIGINT                                  NOT NULL
        CONSTRAINT event_compilations_events_id_fk references events.events,
    compilation_id BIGINT                                  NOT NULL
        CONSTRAINT event_compilations_compilations_id_fk references events.compilations,
    CONSTRAINT pk_event_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events.event_comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id  BIGINT                                  NOT NULL
        CONSTRAINT event_requests_events_id_fk references events.events,
    author_id BIGINT                                  NOT NULL,
    text      VARCHAR(7000),
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status    VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_event_comments PRIMARY KEY (id)
);